### ISSUE TITLE
Add search box auto-complete feature

### ISSUE THREAD

**Issue by raffleberry** [raffleberry/movie-search-engine#2]
#1 

Get your API key from [here](http://www.omdbapi.com/)

1) create a new endpoint for the search API.
2) Use Axios(or anythnig else you prefer) in the front-end.

**Comment by Rajdeepc** [comment]
@raffleberry Can you please assign this to me?

**Comment by raffleberry** [comment]
> @raffleberry Can you please assign this to me?

Sure go ahead.

**Comment by Rajdeepc** [comment]
@raffleberry  The API key is only available to Patrons it seems. Cannot proceed with the development.

**Comment by raffleberry** [comment]
> @raffleberry The API key is only available to Patrons it seems. Cannot proceed with the development.

Let me see if i can get my hands on a key. Will let you know soon.

**Comment by raffleberry** [comment]
> @raffleberry The API key is only available to Patrons it seems. Cannot proceed with the development.

The API key is still available for free [here](http://www.omdbapi.com/apikey.aspx)

**Comment by Rajdeepc** [comment]
@raffleberry Got the key . Please assign this to me.

**Comment by Rajdeepc** [comment]
@raffleberry What is the use case?
Do you want me to create a typeahead box instead of the search form what you currently have?

**Comment by raffleberry** [comment]
> @raffleberry What is the use case?
> Do you want me to create a typeahead box instead of the search form what you currently have?

Sure, that sounds good.
